// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebAPIGoldenData.Data;

#nullable disable

namespace WebAPIGoldenData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIGoldenData.Models.ConsumidorModel", b =>
                {
                    b.Property<int>("IdConsumidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsumidor"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdConsumidor");

                    b.ToTable("CONSUMIDOR");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.FeedbackModel", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ConsumidorIdConsumidor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdFeedback");

                    b.HasIndex("ConsumidorIdConsumidor");

                    b.ToTable("FEEDBACK");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.HistoricoCompraModel", b =>
                {
                    b.Property<int>("IdHistoricoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoricoCompra"));

                    b.Property<int>("ConsumidorIdConsumidor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DataCompra")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ValorCompra")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdHistoricoCompra");

                    b.HasIndex("ConsumidorIdConsumidor");

                    b.ToTable("HISTORICO_COMPRA");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.InfoConsumidorModel", b =>
                {
                    b.Property<int>("IdInfoConsumidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInfoConsumidor"));

                    b.Property<string>("AnunciosEvitados")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CompraOnline")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ConsumidorIdConsumidor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MarcasEvitadas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PreferenciaAnuncio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PreferenciaCompraCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdInfoConsumidor");

                    b.HasIndex("ConsumidorIdConsumidor");

                    b.ToTable("INFO_CONSUMIDOR");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.PagamentoModel", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<int>("HistoricoCompraIdHistoricoCompra")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ValorPagamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("HistoricoCompraIdHistoricoCompra");

                    b.ToTable("PAGAMENTO");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.FeedbackModel", b =>
                {
                    b.HasOne("WebAPIGoldenData.Models.ConsumidorModel", "Consumidor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ConsumidorIdConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.HistoricoCompraModel", b =>
                {
                    b.HasOne("WebAPIGoldenData.Models.ConsumidorModel", "Consumidor")
                        .WithMany("HistoricoCompras")
                        .HasForeignKey("ConsumidorIdConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.InfoConsumidorModel", b =>
                {
                    b.HasOne("WebAPIGoldenData.Models.ConsumidorModel", "Consumidor")
                        .WithMany("InfosConsumidor")
                        .HasForeignKey("ConsumidorIdConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.PagamentoModel", b =>
                {
                    b.HasOne("WebAPIGoldenData.Models.HistoricoCompraModel", "HistoricoCompra")
                        .WithMany("Pagamentos")
                        .HasForeignKey("HistoricoCompraIdHistoricoCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricoCompra");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.ConsumidorModel", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("HistoricoCompras");

                    b.Navigation("InfosConsumidor");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.HistoricoCompraModel", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
