// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebAPIGoldenData.Data;

#nullable disable

namespace WebAPIGoldenData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIGoldenData.Models.ConsumidorModel", b =>
                {
                    b.Property<int>("IdConsumidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsumidor"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdConsumidor");

                    b.ToTable("CONSUMIDOR");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.InfoConsumidorModel", b =>
                {
                    b.Property<int>("IdInfoConsumidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInfoConsumidor"));

                    b.Property<string>("AnunciosEvitados")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CompraOnline")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ConsumidorIdConsumidor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MarcasEvitadas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PreferenciaAnuncio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PreferenciaCompraCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdInfoConsumidor");

                    b.HasIndex("ConsumidorIdConsumidor");

                    b.ToTable("INFO_CONSUMIDOR");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.InfoConsumidorModel", b =>
                {
                    b.HasOne("WebAPIGoldenData.Models.ConsumidorModel", "Consumidor")
                        .WithMany("InfosConsumidor")
                        .HasForeignKey("ConsumidorIdConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("WebAPIGoldenData.Models.ConsumidorModel", b =>
                {
                    b.Navigation("InfosConsumidor");
                });
#pragma warning restore 612, 618
        }
    }
}
